name: Checkout
on: [push]

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files before
              run: ls -a
            - name: Checkout
              run: |
                 git init
                 git remote add origin "https://github.com/Khush-Kelowna/Github-actions.git"
                 git fetch origin
                 git checkout main
            - name: List files After
              run: ls -a
