name: Checkout
on: [push]

jobs:
    checkout-and-display-files:
        runs-on: ubunutu-latest
        steps:
            - name: List files before
              run: ls-a
            - name: Checkout
              run: |
                 git init
                 git remote add origin "https://$GITHUB_ACTOR:${{SECRETS.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                 git fetch origin
                 git checkout main
            - name: List files After
              run: ls -a
